---
- name: Import spoke cluster into hub
  hosts: provisioner
  tasks:
  - name: Check if OC exists
    stat:
      path: /usr/local/bin/oc
    register: oc_path

  - name: Install OC if not present
    block:
      - name: Create temporary directory for oc
        tempfile:
          state: directory
        register: oc_directory

      - name: Download the content
        get_url:
          url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
          dest: "{{ oc_directory.path }}/oc.tar.gz"

      - name: Extract oc binary and copy
        unarchive:
          src: "{{ oc_directory.path }}/oc.tar.gz"
          dest: /usr/local/bin/
          remote_src: yes
    when: oc_path.stat.exists == False

  - name: Create temporary directory for ACM manifests
    tempfile:
      state: directory
    register: acm_directory

  - name: Clone manifests there
    git:
      repo: https://github.com/redhat-ztp/ztp-acm-manifests
      dest: "{{ acm_directory.path }}"

  - name: Copy ACM kubeconfig inside spoke content
    copy:
      src: "{{ kubeconfig_hub_path }}"
      dest: "{{ acm_directory.path }}/spoke_cluster/kubeconfig"

  - name: Apply the content
    command: oc apply -k spoke_cluster
    retries: 10
    delay: 30
    register: apply_result
    until: apply_result.rc == 0
    args:
      chdir: "{{ acm_directory.path }}/"
    environment:
      KUBECONFIG: "{{ kubeconfig_spoke_path }}"

  - name: Remove kubeconfig from tempdir
    file:
      path: "{{ acm_directory.path }}/spoke_cluster/kubeconfig"
      state: absent
